server:
  port: 8087

rabbitmq:
  services:
    - host: docker.nordclan
      port: 34024
  username: kama
  password: kama
  topic: ariston-topic-exchange
  queue-to-send: ariston-queue-to-service
  routing-key-to-send: ariston-routing-key-to-service